version: 0.2  # version of the buildspec process - NOT version of my buildspec

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm ci # 'ci' is faster and safer for CI/CD than 'install'
  build:
    commands:
      - echo "Running the build script..."
      - npm run build  # builds the React app to /dist
  post_build:
    commands:
      # The S3_BUCKET and CF_DISTRIBUTION_ID are environment variables which will be set in CodeBuild
      - echo "Deploying to S3..."
      - aws s3 sync dist/ s3://bakeonomics/spa --delete  # copy in the newly built files; delete anything not in dist
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id E35MZAIKMRD12W --paths "/*"  # this needs to be the path from the server's perspective - it's not the /spa/* s3 directory

#artifacts:  This needs to be omitted - passing in None will fail
#  files:
## None - build phase has taken care of all artefact handling
#
