/**
 * Represents a complete Recipe object with all details.
 * Corresponds to the Python SQLModel `RecipeReadWithDetails`.
 * Optional fields allow this interface to also be used for creating a new recipe.
 */
export interface IRecipe {
    // --- Fields from RecipeRead ---
    recipe_id: number;
    created_timestamp?: string; // Datetimes are serialized as ISO strings
    modified_timestamp?: string;

    // --- Fields from RecipeBase ---
    recipe_name: string;
    recipe_description: string | null;
    recipe_type_id: number | null; // Use null for "not selected" in forms
    product_type_id: number | null;
    recipe_status_id: number | null;
    recipe_uom_id: number | null;
    version: number;
    effective_from_date?: string | null; // Dates are also strings in JSON
    effective_to_date?: string | null;
    is_current: boolean;
    previous_recipe_id: number | null;
    notes: string | null;
    version_notes: string | null;

    // Decimal types are often serialized as strings to preserve precision.
    // Using `string | number` provides flexibility.
    recipe_quantity: string | number;
    yield_percentage: string | number;

    //  note - not nesting in related data (product type, recipe type, uom etc) to simplify the API calls
}

/**
 * Creates a blank, default IRecipe object for populating a new recipe form.
 * @returns A new IRecipe object with default values.
 */
export const createEmptyRecipe = (): IRecipe => {
    return {
        // ID and timestamps are undefined as they are generated by the backend
        recipe_id: 0,  // recipe ID 0 - follow convention used in other forms to identify when a form contains a new item vs. an item being edited
        recipe_name: '',
        recipe_description: '',

        // Foreign keys are all set to default values to prevent type checking errors with API.  todo - add front end logic in form to flag up fields still set to default
        recipe_type_id: 1,
        product_type_id: 1,
        recipe_status_id: 1, // You might set a default status ID here, e.g., 1 for 'Draft'
        recipe_uom_id: 1,

        version: 1,
        is_current: true,

        created_timestamp: '', // e.g., "2025-08-05T20:20:00.000Z"
        modified_timestamp: '',

        // Other nullable fields
        effective_from_date: null,
        effective_to_date: null,
        previous_recipe_id: null,
        notes: null,
        version_notes: null,

        // Numeric/Decimal fields initialized to 0
        recipe_quantity: 1,
        yield_percentage: 100.0,

    };
};